version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ubuntu/new_chatapp
file_exists_behaviour: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu

