version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ubuntu/new_chatapp
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/addFile.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/deleteFile.sh
      timeout: 300
      runass: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu

